package com.example.composestudy.snowball.stockchart.utils

import android.content.Context
import android.text.TextUtils
import android.util.Log
import com.example.composestudy.snowball.stockchart.data.KLinePriceData
import com.example.composestudy.snowball.stockchart.data.MinuteTimePriceData
import com.google.gson.Gson
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonSyntaxException
import com.google.gson.reflect.TypeToken
import java.io.*
import java.lang.StringBuilder

fun generateMinuteTimeData(context: Context): MinuteTimePriceData? {
    // 返回默认json文件中配置的值
    val defaultStr = readAssets2String(context, "demo-mock-minute.json")
    if (!TextUtils.isEmpty(defaultStr)) {
        val gson = Gson()
        try {
            return gson.fromJson(defaultStr, MinuteTimePriceData::class.java)
        } catch (e: JsonSyntaxException) {
            Log.e("MinuteTimeData:", "error")
        }
    }
    return null
}


fun generateKLineData(context: Context): List<KLinePriceData> {
    // 返回默认json文件中配置的值
    val defaultStr = readAssets2String(context, "demo-mock-kline.json")
    if (!TextUtils.isEmpty(defaultStr)) {
        val gson = Gson()
        try {
            val obj = gson.fromJson(defaultStr, JsonObject::class.java)
            val columnObj: JsonArray = obj.getAsJsonArray("column") ?: return ArrayList()
            val columns: MutableList<String> = ArrayList()
            for (i in 0 until columnObj.size()) {
                columns.add(columnObj[i].asString)
            }
            val resultArray = JsonArray()
            val items = obj.getAsJsonArray("item")
            for (i in 0 until items.size()) {
                val sourceItem = items[i].asJsonArray
                val klineItem = JsonObject()
                for (j in columns.indices) {
                    klineItem.add(columns[j], sourceItem[j])
                }
                resultArray.add(klineItem)
            }
            val type = object : TypeToken<List<KLinePriceData?>?>() {}.type
            return gson.fromJson(resultArray, type)
        } catch (e: JsonSyntaxException) {
            Log.e("KLineData:", "error")
        }
    }
    return ArrayList()
}

fun readAssets2String(context: Context, assetsFilePath: String?): String {
    if (assetsFilePath.isNullOrEmpty()) {
        return ""
    }
    try {
        val file = context.assets.open(assetsFilePath)
        val stringBuilder = StringBuilder()
        val inputStream = InputStreamReader(file)
        val buffer = BufferedReader(inputStream)
        var line: String?  = ""
        while (line != null ) {
            stringBuilder.append(line)
            line = buffer.readLine()
        }

        return stringBuilder.toString()
    } catch (var6: IOException) {
        var6.printStackTrace()
    }
    return ""
}

//fun initMinuteData(): List<Float> {
//    val list = mutableListOf<Float>()
//    list.add(1217.45f)
//    list.add(1217.95f)
//    list.add(1217.65f)
//    list.add(1217.05f)
//    list.add(1216.33f)
//    list.add(1217.15f)
//    list.add(1217.65f)
//    list.add(1218.45f)
//    list.add(1218.99f)
//    list.add(1219.15f)
//
//    list.add(1219.25f)
//    list.add(1219.55f)
//    list.add(1219.95f)
//    list.add(1219.65f)
//    list.add(1219.05f)
//    list.add(1218.85f)
//    list.add(1218.05f)
//    list.add(1218.55f)
//    list.add(1218.99f)
//    list.add(1218.33f)
//
//    list.add(1217.55f)
//    list.add(1218.22f)
//    list.add(1218.85f)
//    list.add(1219.55f)
//    list.add(1219.98f)
//    list.add(1220.55f)
//    list.add(1220.95f)
//    list.add(1221.15f)
//    list.add(1221.35f)
//    list.add(1221.61f)
//
//    list.add(1219.00f)
//    list.add(1218.77f)
//    list.add(1218.55f)
//    list.add(1218.45f)
//    list.add(1218.35f)
//    list.add(1218.55f)
//    list.add(1218.11f)
//    list.add(1217.55f)
//    list.add(1217.05f)
//    list.add(1217.99f)
//
//    list.add(1217.88f)
//    list.add(1217.66f)
//    list.add(1217.77f)
//    list.add(1217.85f)
//    list.add(1217.55f)
//    list.add(1217.44f)
//    list.add(1217.33f)
//    list.add(1217.22f)
//    list.add(1217.11f)
//    list.add(1217.00f)
//
//    list.add(1217.06f)
//    list.add(1217.11f)
//    list.add(1217.20f)
//    list.add(1217.28f)
//    list.add(1217.38f)
//    list.add(1217.44f)
//    list.add(1217.55f)
//    list.add(1217.64f)
//    list.add(1217.70f)
//    list.add(1217.78f)
//
//    list.add(1217.88f)
//    list.add(1217.95f)
//    list.add(1218.08f)
//    list.add(1218.33f)
//    list.add(1218.55f)
//    list.add(1218.65f)
//    list.add(1218.75f)
//    list.add(1218.85f)
//    list.add(1219.95f)
//    list.add(1219.05f)
//
//    list.add(1219.15f)
//    list.add(1219.25f)
//    list.add(1219.35f)
//    list.add(1219.45f)
//    list.add(1219.55f)
//    list.add(1219.65f)
//    list.add(1219.75f)
//    list.add(1219.85f)
//    list.add(1219.95f)
//    list.add(1220.1f)
//
//    list.add(1220.2f)
//    list.add(1220.3f)
//    list.add(1220.4f)
//    list.add(1220.5f)
//    list.add(1220.6f)
//    list.add(1220.7f)
//    list.add(1220.8f)
//    list.add(1220.9f)
//    list.add(1221.1f)
//    list.add(1221.2f)
//
//    list.add(1220.2f)
//    list.add(1220.3f)
//    list.add(1220.4f)
//    list.add(1220.5f)
//    list.add(1220.6f)
//    list.add(1220.7f)
//    list.add(1220.8f)
//    list.add(1220.9f)
//    list.add(1221.1f)
//    list.add(1221.2f)
//    return list
//}
//
//fun initKLineData(): ArrayList<KLinePriceData> {
//    val dataListKLine: ArrayList<KLinePriceData> = ArrayList()
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//
//    dataListKLine.add(
//        KLinePriceData(
//            300f,
//            100f,
//            340f,
//            60f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            120f,
//            170f,
//            190f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            144f,
//            150f,
//            90f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            130f,
//            100f,
//            150f,
//            80f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            110f,
//            170f,
//            200f,
//            100f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            170f,
//            220f,
//            230f,
//            160f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            210f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            270f,
//            299f,
//            311f,
//            266f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            290f,
//            333f,
//            344f,
//            290f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            329f,
//            350f,
//            377f,
//            321f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            346f,
//            422f,
//            470f,
//            346f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            433f,
//            400f,
//            444f,
//            388f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            390f,
//            340f,
//            400f,
//            330f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            360f,
//            320f,
//            369f,
//            311f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            311f,
//            288f,
//            322f,
//            270f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            295f,
//            269f,
//            296f,
//            250f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            266f,
//            243f,
//            277f,
//            222f
//        )
//    )
//    dataListKLine.add(
//        KLinePriceData(
//            230f,
//            269f,
//            277f,
//            199f
//        )
//    )
//    return dataListKLine
//}